from __future__ import annotations
from enum import Enum
from typing import Any, Mapping, Protocol, Self
from dataclasses import dataclass
import json

SCHEMA_VERSION: int = 1

class EventType(str, Enum):
    MARKET = "market"
    ORDER_INTENT = "order_intent"
    ORDER_EVENT = "order_event"
    FILL = "fill"

class Side(str, Enum):
    BUY = "buy"
    SELL = "sell"

class OrderType(str, Enum):
    MARKET = "market"
    LIMIT = "limit"

class TimeInForce(str, Enum):
    GTC = "gtc"            # Good-Till-Cancel
    IOC = "ioc"            # Immediate-Or-Cancel
    FOK = "fok"            # Fill-Or-Kill

class OrderStatus(str, Enum):
    NEW = "new"            # created locally (intent exists)
    SENT = "sent"          # sent to gateway
    ACK = "ack"            # exchange acknowledged
    REJECT = "reject"      # exchange rejected
    PARTIAL = "partial"    # partially filled
    FILLED = "filled"      # fully filled
    CANCELED = "canceled"  # canceled confirmed

class Event(Protocol):
    """Minimum interface every event must provide."""
    v: int
    type: EventType
    symbol: str
    seq: int
    ts_recv_ns: int

    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

@dataclass(frozen=True, slots=True)
class BaseEvent:
    """
    Base fields shared by all events.
    
    - v: schema version
    - seq: local monotonically increasing sequence number (for gap detection)
    - ts_recv_ns: local receive time in ns (monotonic or wall: choose one consistently)
    """
    v: int
    type: EventType
    symbol: str
    seq: int
    ts_recv_ns: int

    def to_dict(self) -> dict[str, Any]: 
        # dataclass.asdict is slower & allocates more; do it explicitly
        return {
            "v": self.v,
            "type": self.type.value,
            "symbol": self.symbol,
            "seq": self.seq,
            "ts_recv_ns": self.ts_recv_ns,
        }

    def to_json(self) -> str:
        # compact JSON for ndjson logging
        return json.dumps(self.to_dict(), separators=(",", ":"), ensure_ascii=False)
    
@dataclass(frozen=True, slots=True)
class MarketEvent(BaseEvent):
    """
    Normalized market data event (start simple: L1/top-of-book or trade).

    ts_exchange_ns: exchange timestamp if available(ns). 0 if unknown.
    bid/ask/last may be 0.0 when not provided by the feed/
    """
    ts_exchange_ns: int = 0
    bid: float = 0.0
    ask: float = 0.0
    last: float = 0.0
    bid_sz: float = 0.0
    ask_sz: float = 0.0
    last_sz: float = 0.0
    source: str = "unknown"

    @classmethod
    def new(
        cls,
        *,
        symbol: str,
        seq: int,
        ts_recv_ns: int,
        ts_exchange_ns: int = 0,
        bid: float = 0.0,
        ask: float = 0.0,
        last: float = 0.0,
        bid_sz: float = 0.0,
        ask_sz: float = 0.0,
        last_sz: float = 0.0,
        source: str = "unknown",
        v: int = SCHEMA_VERSION,
    ) -> Self:
        return cls(
            v = v,
            type = EventType.MARKET,
            symbol = symbol,
            seq = seq,
            ts_recv_ns = ts_recv_ns,
            ts_exchange_ns = ts_exchange_ns,
            bid = bid,
            ask = ask,
            last = last,
            bid_sz = bid_sz,
            ask_sz = ask_sz,
            last_sz = last_sz,
            source = source,
        )

    def to_dict(self) -> dict[str, Any]:
        d = super().to_dict()
        d.update(
            {
                "ts_exchange_ns": self.ts_exchange_ns,
                "bid": self.bid,
                "ask": self.ask,
                "last": self.last,
                "bid_sz": self.bid_sz,
                "ask_sz": self.ask_sz,
                "last_sz": self.last_sz,
                "source": self.source,
            }
        )
        return d

@dataclass(frozen=True, slots=True)
class OrderIntent(BaseEvent):
    """
    Intent is produced by core/strategy and consumed by execution gateway.

    intent_id: end-to-end id generated by core, used for idempotency & correlation.
    client_order_id: optional; if exchange supports custom id, set it to intent_id or derived.
    """
    intent_id: str = ""
    side: Side = Side.BUY
    qty: float = 0.0
    order_type: OrderType = OrderType.LIMIT
    limit_px: float | None = None
    tif: TimeInForce = TimeInForce.GTC

    # optional metadata
    strategy: str = "demo"
    reason: str = "" # why we placed it (for debugging)

    @classmethod
    def new(
        cls,
        *,
        symbol: str,
        seq: int,
        ts_recv_ns: int,
        intent_id: str,
        side: Side,
        qty: float,
        order_type: OrderType = OrderType.LIMIT,
        limit_px: float | None = None,
        tif: TimeInForce = TimeInForce.GTC,
        strategy: str = "demo",
        reason: str = "",
        v: int = SCHEMA_VERSION,
    ) -> Self:
        return cls(
            v = v,
            type = EventType.ORDER_INTENT,
            symbol = symbol,
            seq = seq,
            ts_recv_ns = ts_recv_ns,
            intent_id = intent_id,
            side = side,
            qty = qty,
            order_type = order_type,
            limit_px = limit_px,
            tif = tif,
            strategy = strategy,
            reason = reason,
        )

    def to_dict(self) -> dict[str, Any]:
        d = super().to_dict()
        d.update(
            {
                "intent_id": self.intent_id,
                "side": self.side.value,
                "qty": self.qty,
                "order_type": self.order_type.value,
                "limit_px": self.limit_px,
                "tif": self.tif.value,
                "strategy": self.strategy,
                "reason": self.reason,
            }
        )
        return d

@dataclass(frozen=True, slots=True)
class OrderEvent(BaseEvent):
    """
    Execution gateway -> core: ack/reject/cancel/status updates.
    """
    intent_id: str = ""
    status: OrderStatus = OrderStatus.ACK

    # exchange identifiers
    exchange_order_id: str = ""
    client_order_id: str = ""

    # timing
    ts_send_ns: int = 0         # when gateway sent
    ts_exchange_ns: int = 0     # exchange timestamp if provided

    # optional error info
    error_code: str = ""
    error_msg: str = ""

    def to_dict(self) -> dict[str, Any]:
        d = super().to_dict()
        d.update(
            {
                "intent_id": self.intent_id,
                "status": self.status.value,
                "exchange_order_id": self.exchange_order_id,
                "client_order_id": self.client_order_id,
                "ts_send_ns": self.ts_send_ns,
                "ts_exchange_ns": self.ts_exchange_ns,
                "error_code": self.error_code,
                "error_msg": self.error_msg
            }
        )
        return d
    
@dataclass(frozen=True, slots=True)
class FillEvent(BaseEvent):
    """
    Execution gateway -> core: fills (partial/full).
    """
    intent_id: str = ""
    exchange_order_id: str = ""
    side: Side = Side.BUY

    fill_px: float = 0.0
    fill_qty: float = 0.0
    fee: float = 0.0
    fee_ccy: str = ""

    ts_send_ns: int = 0
    ts_exchange_ns: int = 0

    def to_dict(self) -> dict[str, Any]:
        d = super().to_dict()
        d.update(
            {
                "intent_id": self.intent_id,
                "exchange_order_id": self.exchange_order_id,
                "side": self.side.value,
                "fill_px": self.fill_px,
                "fill_qty": self.fill_qty,
                "fee": self.fee,
                "fee_ccy": self.fee_ccy,
                "ts_send_ns": self.ts_send_ns,
                "ts_exchange_ns": self.ts_exchange_ns
            }
        )
        return d

